---
- name: restart calert
  become: true
  systemd:
      daemon_reload: true
      name: calert
      state: restarted

- name: reload calert
  become: true
  systemd:
      name: calert
      state: reloaded
