---
#
# Playbook to install the Node exporter and Filebeat in individual app servers
#
- hosts: "{{node_host}}"
  remote_user: "{{node_user}}"
  become: yes
  vars_files:
  - vars.yml
  # become_user: "{{node_user}}"
  roles:
  - { role: filebeat }
  - { role: node_exporter }
