---
# Role to install node_exporter (Takes ideas from https://github.com/cloudalchemy/ansible-alertmanager)


- name: create alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ alertmanager_config_dir }}"
    - "{{ alertmanager_config_dir }}/templates"
    - "{{ alertmanager_db_dir }}"

- name: download alertmanager binary to local folder
  become: false
  unarchive:
    src: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/alertmanager"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  # run_once: true
  delegate_to: localhost

- name: propagate alertmanager and amtool binaries
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    # owner: alertmanager
    # group: alertmanager
  with_items:
    - alertmanager
    - amtool
  notify:
    - restart alertmanager

- name: remove alertmanager binaries from old location
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/alertmanager/alertmanager
    - /opt/alertmanager/amtool
    - /opt/alertmanager

- name: create systemd service unit
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart alertmanager