prometheus_user: root
prometheus_db_dir: /var/lib/prometheus/
prometheus_config_dir: /etc/prometheus/prometheus.yml
prometheus_version: 2.5.0
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'