---
# Role to install calert (https://github.com/mr-karan/calert)

- name: create calert directories
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  with_items:
      - "{{ calert_config_dir }}"

- name: ensure tmp calert directory exists
  file:
      path: /tmp/calert/
      state: directory

- name: download calert binary to local folder
  unarchive:
      src: "https://github.com/mr-karan/calert/releases/download/v{{ calert_version }}/calert_{{ calert_version }}_Linux_{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
      dest: /tmp/calert/
      remote_src: yes

- name: propagate calert binary file
  copy:
      src: "/tmp/calert/{{item}}"
      dest: "/usr/local/bin/{{item}}"
      mode: 0755
      remote_src: yes
  with_items:
      - calert

- name: propagate calert config files
  copy:
      src: "/tmp/calert/{{item}}"
      dest: "{{calert_config_dir}}/config.toml"
      mode: 0755
      remote_src: yes
  with_items:
      - config.toml.sample

- name: create systemd service unit
  template:
      src: calert.service.j2
      dest: /etc/systemd/system/calert.service
      owner: root
      group: root
      mode: 0644

- name: Starting calert as a service
  service:
      name: calert
      state: started
      enabled: yes

- name: Cleanup tmp folder for calert
  file:
      state: absent
      path: /tmp/calert
