---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'
alertmanager_user: root
alertmanager_db_dir: /var/lib/alertmanager/
alertmanager_config_dir: /etc/alertmanager
alertmanager_version: 0.15.3
alertmanager_config_file: 'alertmanager.yml.j2'
